### ISSUE TITLE
`after` hook not firing reliably

### ISSUE THREAD

**Issue by searls** [balderdashy/waterline-adapter-tests#32] opened 2015-02-04 00:06 UTC
In order for our tests to behave consistently, the after hooks for each suite need to execute consistently (so we can dump our database). What I'm finding is that when I run my suite with `npm test`, the after hooks (like [this one](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/semantic/support/bootstrap.js#L46-L62)) are not firing.

However if I grab an individual test like [this one](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/semantic/create.test.js#L6) and set it to `describe.only`, then the after hook will fire just fine.

Any insight into this?

**Comment by searls** [comment] 2015-02-04 00:09
Ah, so it would seem that this is a mocha issue, reopened as recently as 20 hours ago. Wow.

https://github.com/mochajs/mocha/issues/534

**Comment by dasilvacontin** [comment] 2015-02-04 01:08
@searls, is it possible that the (async) before hook is failing? Because yesterday I found out that it bugs the run.

**Comment by searls** [comment] 2015-02-04 02:25
There is no evidence that one is failing. It seems happy right up to the point it calls `done()`

**Comment by dasilvacontin** [comment] 2015-02-04 02:29
When it calls `done` inside the after? What happens then?

**Comment by searls** [comment] 2015-02-04 02:29
The after is never invoked if I run the whole suite.

**Comment by dasilvacontin** [comment] 2015-02-04 03:13
Hmm, not sure if it's related to the bug I found.

**Comment by searls** [comment] 2015-02-04 03:14
(subtext: because the suite is erroring. when i run just a passing or failing subset of the suite, the after is invoked)

**Comment by dasilvacontin** [comment] 2015-02-04 03:30
The suite is erroring? Where?

**Comment by searls** [comment] 2015-02-04 03:32
Okay I think we need to back up. I'm currently implementing [this repo](https://github.com/testdouble/waterline-parse), which in turn is using this repo's test suite as a guide to figuring out how I need to implement it.

Because my adapter is half-implemented, most of the tests are going to be failing most of the time. I suspect that whenever a failure occurs due to an error being thrown, the suite's `after` hook does not fire. That is to say, `after` doesn't fire at all unless I intentionally run just one test or suite that I know to be passing (or failing logically and not throwing an error)

**Comment by dasilvacontin** [comment] 2015-02-04 03:36
I see. What I've confirmed so far (and I'm currently fixing and adding new tests so that it doesn't happen again) is that an async failure in either a before hook or a test causes the after hook not to fire. We probably stopped setting up the uncaught exception handler at some point. Looking into it. :shipit:

**Comment by searls** [comment] 2015-02-04 03:37
That sounds about right. Apologies for the vague and probably overly-terse descriptions on my end (when we hopped repos I wasn't sure if you were representing Mocha or Sails)

**Comment by dasilvacontin** [comment] 2015-02-04 04:07
No worries! Glad to help!

**Comment by CWyrtzen** [comment] 2015-03-11 22:02
Howdy folks, is this resolved now?

**Comment by dasilvacontin** [comment] 2015-03-11 22:46
I've been very busy lately, so I personally haven't been able to further investigate/make progress.

**Comment by dmarcelino** [comment] 2015-03-24 18:33
@searls, can you please try using the latest version of waterline-adapter-tests in master branch and filter out the broken tests using the example in #35? Let us know if that fixes this issue. Thanks

**Comment by dmarcelino** [comment] 2015-04-24 11:07
Closing this as abandoned, please reopen if you are still experiencing this.

**Closed by dmarcelino** 2015-04-24 11:07 UTC
